apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-jeff
  labels:
    app: python-app-jeff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-jeff
  template:
    metadata:
      labels:
        app: python-app-jeff
    spec:
      containers:
      - name: python-app-jeff
        image: kittyiv/python-app-jeff:v2
        ports:
        - containerPort: 5000
