apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-jeff
spec:
  rules:
  - host: "python-app-jeff.test.com"
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-app-jeff
            port:
              number: 8080
