apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-app-jeff-runners
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-app-helm-deployer
  namespace: python
subjects:
  - kind: ServiceAccount
    name: python-app-jeff-runners
    namespace: actions-runner-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
